version: "3.6"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret_passs
      MYSQL_DATABASE: app_db
      MYSQL_USER: php_web
      MYSQL_PASSWORD: devp@ss
    expose:
        - "3306"
    volumes:
    - mysql:/var/lib/mysql
  
  web:
    build: .
    ports:
     - 8086:80

volumes:
  mysql: